version: '3.3'

volumes:
  rversions-data:
  certbot-etc:
  certbot-var:
  web-root:

secrets:
  app-insights-key:
    external: true

services:

  rversions:
    image: "rhub/api-rversions:0.0.7"
    environment:
      - REDIS_HOST=rversions-redis
      - PORT=3000
#    secrets:
#      - app-insights-key
    depends_on:
      - rversions-redis
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: curl -s http://127.0.0.1:3000/r-release >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50

  rversions-redis:
    image: "redis:4.0.11-alpine"
    volumes:
      - rversions-data:/data
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure

  nginx:
    build: "./nginx"
    image: "rhub/api-nginx:0.0.1"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html:ro
      - certbot-etc:/etc/letsencrypt:ro
      - certbot-var:/var/lib/letsencrypt:ro
    depends_on:
      - rversions
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
    entrypoint:
      - sh
      - -c
      - /entrypoint.sh

  certbot:
    image: "certbot/certbot"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
#   command: certonly --webroot --webroot-path=/var/www/html --email csardi.gabor@gmail.com --agree-tos --no-eff-email -d api.r-hub.io
    command: renew
    deploy:
      restart_policy:
        condition: any
        delay: 24h
