
FROM busybox:latest

COPY entrypoint.sh /entrypoint.sh
COPY api.r-hub.io+3.pem /api.r-hub.io+3.pem
COPY api.r-hub.io+3-key.pem /api.r-hub.io+3-key.pem
COPY search.r-pkg.org+3.pem /search.r-pkg.org+3.pem
COPY search.r-pkg.org+3-key.pem /search.r-pkg.org+3-key.pem
